import { Itinerary } from "../types";
import { motion, AnimatePresence } from "framer-motion";
import { Share2, Mail, MessageSquare, Copy, Check, X, Download } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

interface ShareItineraryProps {
  itinerary: Itinerary;
  onClose: () => void;
}

export function ShareItinerary({ itinerary, onClose }: ShareItineraryProps) {
  const [copied, setCopied] = useState(false);

  const generateSummary = () => {
    let summary = `📍 Itinerary for ${itinerary.destination}\n`;
    summary += `📅 Duration: ${itinerary.days.length} Days\n`;
    summary += `💰 Budget: ₹${itinerary.budgetRs}\n\n`;
    
    itinerary.days.forEach(day => {
      summary += `Day ${day.day}:\n`;
      day.places.forEach(place => {
        summary += `- ${place.name} (${place.time_required})\n`;
      });
      summary += `🍴 Food: ${day.food}\n`;
      summary += `🏨 Stay: ${day.hotel}\n\n`;
    });

    summary += `Generated by Itinno AI Travel Planner`;
    return summary;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateSummary());
      setCopied(true);
      toast.success("Itinerary copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error("Failed to copy itinerary");
    }
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`My Travel Plan for ${itinerary.destination}`);
    const body = encodeURIComponent(generateSummary());
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const handleWhatsApp = () => {
    const text = encodeURIComponent(generateSummary());
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const handleNativeShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Trip to ${itinerary.destination}`,
          text: generateSummary(),
          url: window.location.origin
        });
      } catch (err) {
        console.error("Native share failed:", err);
      }
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm"
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.9, opacity: 0, y: 20 }}
        className="bg-surface w-full max-w-md rounded-[2rem] border border-text/10 shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-8">
          <div className="flex justify-between items-center mb-8">
            <div>
              <h3 className="text-2xl font-serif font-bold text-text">Share Journey</h3>
              <p className="text-sm text-text/50">Send your {itinerary.destination} plan to friends.</p>
            </div>
            <button 
              onClick={onClose}
              className="p-2 hover:bg-text/5 rounded-full transition-colors"
            >
              <X className="w-6 h-6 text-text/40" />
            </button>
          </div>

          <div className="grid grid-cols-2 gap-4 mb-8">
            <button
              onClick={handleEmail}
              className="flex flex-col items-center gap-3 p-6 rounded-2xl bg-background/50 border border-text/5 hover:border-primary/30 hover:bg-primary/5 transition-all group"
            >
              <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary group-hover:scale-110 transition-transform">
                <Mail className="w-6 h-6" />
              </div>
              <span className="text-sm font-bold text-text">Email</span>
            </button>

            <button
              onClick={handleWhatsApp}
              className="flex flex-col items-center gap-3 p-6 rounded-2xl bg-background/50 border border-text/5 hover:border-green-500/30 hover:bg-green-500/5 transition-all group"
            >
              <div className="w-12 h-12 rounded-xl bg-green-500/10 flex items-center justify-center text-green-500 group-hover:scale-110 transition-transform">
                <MessageSquare className="w-6 h-6" />
              </div>
              <span className="text-sm font-bold text-text">WhatsApp</span>
            </button>

            <button
              onClick={handleCopy}
              className="flex flex-col items-center gap-3 p-6 rounded-2xl bg-background/50 border border-text/5 hover:border-accent/30 hover:bg-accent/5 transition-all group"
            >
              <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center text-accent group-hover:scale-110 transition-transform">
                {copied ? <Check className="w-6 h-6" /> : <Copy className="w-6 h-6" />}
              </div>
              <span className="text-sm font-bold text-text">{copied ? "Copied!" : "Copy Text"}</span>
            </button>

            {navigator.share && (
              <button
                onClick={handleNativeShare}
                className="flex flex-col items-center gap-3 p-6 rounded-2xl bg-background/50 border border-text/5 hover:border-secondary/30 hover:bg-secondary/5 transition-all group"
              >
                <div className="w-12 h-12 rounded-xl bg-secondary/10 flex items-center justify-center text-secondary group-hover:scale-110 transition-transform">
                  <Share2 className="w-6 h-6" />
                </div>
                <span className="text-sm font-bold text-text">System Share</span>
              </button>
            )}
          </div>

          <div className="bg-background/30 rounded-2xl p-4 border border-text/5">
            <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-text/30 mb-2">
              <Download className="w-3 h-3" />
              Preview Summary
            </div>
            <div className="text-[11px] text-text/60 line-clamp-4 whitespace-pre-wrap font-mono">
              {generateSummary()}
            </div>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
